### ISSUE TITLE
Add link to Google oss doc

### ISSUE THREAD

**Issue by mikofski** [thehackerwithin/berkeley#102]
Add [this link](https://opensource.google.com/docs/why/)
 to 2017-10-04-github-oss-f17.md

**Comment by mikofski** [comment]
Here: https://github.com/thehackerwithin/berkeley/blob/master/docs/_posts/2017-10-04-github-oss-f17.md

**Comment by diyadas** [comment]
@mikofski Could you submit a PR with this change?
