### ISSUE TITLE
Request for session: interactive visualization (D3?)

### ISSUE THREAD

**Issue by staeiou** [thehackerwithin/berkeley#111]

**Comment by rlbarter** [comment]
I'm a super beginner D3 user but if you can't find anyone else who actually is good at D3, I'd be down to run this one!

**Comment by diyadas** [comment]
Maybe @cypranowska can help?

**Comment by cypranowska** [comment]
I've made a few things in D3, and would love to help

**Comment by staeiou** [comment]
Hey @rlbarter @cypranowska -- are either/both of you still interested? Dates are pretty open (http://www.thehackerwithin.org/berkeley/upcoming.html)

**Comment by cypranowska** [comment]
I have a map-making example/tutorial that I can prepare for Feb 28. @rlbarter are you interested in co-presenting? We can split this up into an intro to D3 concepts and then a hands-on example, or something.

**Comment by rlbarter** [comment]
I'm giving an unrelated ggplot presentation on Feb 28. I'm also have to start to prepare for my qualifying exam so I might have to withdraw my original enthusiasm until after I'm done :( Sorry team!!

**Comment by cypranowska** [comment]
@rlbarter Good luck on your presentation and good luck studying!

**Comment by staeiou** [comment]
Thanks and good luck! Closed in #121
