### ISSUE TITLE
IPython talk

### ISSUE THREAD

**Issue by kellyrowland** [thehackerwithin/berkeley#30]
I realize that this is slightly last-minute, so I do apologize...

For the IPython talk on February 25, would it be possible to go over some of the complete and total basics of the IPython notebooks (creating one, launching it in-browser, etc.)?

@minrk @takluyver

**Comment by takluyver** [comment]
I think we've arranged it in private and forgotten to tell anyone else - @omoju is actually going to be leading the session on IPython tomorrow, not us.

@minrk, @Carreau and myself will all be around, though, so if people have specific questions, we'll make sure there are specific answers. :-)

**Comment by omoju** [comment]
Hello @kellyrowland Sorry we didn't update the whole group. I will go over the basics of Ipython Notebooks, as well as why it is more advantageous for us all to use them.

**Comment by kellyrowland** [comment]
Great, thanks for the update and info!
