### ISSUE TITLE
Anyone feel strongly about submodules?

### ISSUE THREAD

**Issue by tkelman** [thehackerwithin/berkeley#59]
Working on my talk for this week's meeting, and doing most of the demos in a separate repo since I'm using an actual C library as an example. I'm thinking of adding it as a submodule under an appropriate folder here. Anyone opposed to that plan, if I put in a README comment explaining how to make git do the right thing?

**Comment by katyhuff** [comment]
Go for it!

**Comment by tkelman** [comment]
will finish in #60 then
