### ISSUE TITLE
wrong start year for 'previous' posts

### ISSUE THREAD

**Issue by kellyrowland** [thehackerwithin/berkeley#64]
website has previous posts listed as '2015-2016', but there are definitely some dating back to 2014. :)

gave a 30-second pass through and couldn't find where to change that, and thus this issue was opened.

**Comment by staeiou** [comment]
Good eye! Now fixed in 74c7b4e

**Comment by kellyrowland** [comment]
Thanks for the fix! I'm not sure I ever would have figured out that particular change would make a difference. :)
