### ISSUE TITLE
2017 Feb 7th discussion "introduction to python"

### ISSUE THREAD

**Issue by rainwoodman** [thehackerwithin/berkeley#73]
Co-leaders:

- We shall get together this week (e.g. on Thursday) to decide on the materials and logistics.

- Some jump start material is at http://swcarpentry.github.io/python-novice-inflammation/; but it is a four hour lecture. We can't do that much.

- We shall spend some time setting up a Python distribution for the attendees. (e.g. anaconda) A GUI is useful, so Jupyter notebook.

For the actually 'Introduction to Python programming', a few things that popped into my mind are:

- What is computer programming? How does it differ and assimilate with mathematics?

- The confused `equal` sign. L-value and R-value.

- Identity of objects, internal state and immutability

- Functions & Recursion

- Control structures. Conditionals and Loops. -- How does this fit into a functional perspective of programming?

- Dealing with Tensors (Arrays)

- Strings and their representations, encoding, unicode, bytes.

Probably way too heavy for an intro ...

**Comment by staeiou** [comment]
closed in e7995c5
